TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

CFG += MODULE

#==================================================
# build a support library

# LIBRARY_IOC = MODULE


# MODULE_SRCS += a_file.cpp


# MODULE_LIBS += dependent_lib
# MODULE_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
